## «*Olvidaba que en todo combate entre el fanatismo y el sentido común, pocas veces logra este último imponerse*».
### [Marguerite Yourcenar](https://es.wikipedia.org/wiki/Marguerite_Yourcenar)

# ppi_SI_05_NumPy

Actividad individual.

Utilice el dataset seleccionado en **SI01 Repositorio csv de Kaggle**.

Diligencie las casillas indicadas siguiendo las normas de estilo del PEP8.

# NOTA
*   Se agregó título a la primera columna "Índice"
*   Se añadieron 0 en los espacios vacíos y en los valores N/A
*   Se cambiaron las , por ;

# Preparación del ejercicio

*   Importe las librerías requeridas
*   Lea el dataset a utilizar desde una url

Sugerencia: suba el dataset a Googledrive y luego publíquelo como página web. El siguiente enlace le indica cómo hacerlo: [Cómo publicar archivos de Documentos, Hojas de cálculo, Presentaciones y Formularios de Google](https://support.google.com/docs/answer/183965?hl=es-419&co=GENIE.Platform%3DDesktop).

Nota: si lo desea puede utilizar otro método para obtener la url del dataset.



In [ ]:
# Instalando el pep8
!pip install pycodestyle
!pip install --index-url https://test.pypi.org/simple/ nbpep8

Looking in indexes: https://test.pypi.org/simple/


In [ ]:
# Importar las librerías necesarias
import numpy as np
from nbpep8.nbpep8 import pep8

# Conocer la versión de la librería NumPy instalada
print(f'Versión de NumPy: {np.__version__}')

# URL del archivo CSV
ruta = "https://docs.google.com/spreadsheets/d/e/2PACX-1vTQhpVFGQ\
HgTIEf0DX2c24PPtal6Pl-Ro-x0MAM_8NEcKT7WNgOUsG7dWuwK91BiXv2QQUWaTRE\
GPky/pub?output=csv"

# Cargar el archivo CSV utilizando NumPy
peliculas_disney = np.genfromtxt(ruta, delimiter=',', dtype=str)

# Verificar la lectura del dataset
print(peliculas_disney)
pep8(_ih)

Versión de NumPy: 1.23.5
[['Índice' 'title' 'Production company' ... 'Adaptation by' 'Traditional'
  'Simplified']
 ['0' 'Academy Award Review of' 'Walt Disney Productions' ... '0' '0' '0']
 ['1' 'Snow White and the Seven Dwarfs' 'Walt Disney Productions' ... '0'
  '0' '0']
 ...
 ['429' 'Cruella'
  "('Walt Disney Pictures'; 'Gunn Films'; 'Marc Platt Productions')" ...
  '0' '0' '0']
 ['430' 'Jungle Cruise'
  "('Walt Disney Pictures'; 'Davis Entertainment'; 'Seven Bucks Productions'; 'Flynn Picture Company')"
  ... '0' '0' '0']
 ['431' 'The Beatles: Get Back' '0' ... '0' '0' '0']]



# Explorar el dataset

Muestre las principales características del dataset.

In [ ]:
# Imprimir el arreglo 'peliculas_disney' y sus características
print(f"Esta es el arreglo: \n{peliculas_disney} \n")
print("Estas son las principales características del dataset: ")

# Obtener y mostrar la forma del arreglo peliculas_disney
forma_arreglo = peliculas_disney.shape
print(f"La forma del arreglo es: {forma_arreglo}")

# Obtener y mostrar la dimensión del arreglo peliculas_disney
dimension_arreglo = peliculas_disney.ndim
print(f"La dimensión del arreglo es: {dimension_arreglo}")

# Obtener y mostrar el número de filas y columnas del arreglo\
# peliculas_disney
num_filas = forma_arreglo[0]
num_columnas = forma_arreglo[1]
print(f"El arreglo tiene {num_filas} filas")
print(f"El arreglo tiene {num_columnas} columnas.")
pep8(_ih)

Esta es el arreglo: 
[['Índice' 'title' 'Production company' ... 'Adaptation by' 'Traditional'
  'Simplified']
 ['0' 'Academy Award Review of' 'Walt Disney Productions' ... '0' '0' '0']
 ['1' 'Snow White and the Seven Dwarfs' 'Walt Disney Productions' ... '0'
  '0' '0']
 ...
 ['429' 'Cruella'
  "('Walt Disney Pictures'; 'Gunn Films'; 'Marc Platt Productions')" ...
  '0' '0' '0']
 ['430' 'Jungle Cruise'
  "('Walt Disney Pictures'; 'Davis Entertainment'; 'Seven Bucks Productions'; 'Flynn Picture Company')"
  ... '0' '0' '0']
 ['431' 'The Beatles: Get Back' '0' ... '0' '0' '0']] 

Estas son las principales características del dataset: 
La forma del arreglo es: (430, 31)
La dimensión del arreglo es: 2
El arreglo tiene 430 filas
El arreglo tiene 31 columnas.



# Transformar el dataset


## arreglo_00

Cree el arreglo_00 con las siguientes características:

*  seis columnas (dentro de las seis columnas deben estar la primera y la última columna del dataset original)
*  veinte filas (las filas deben corresponder a las diez primeras filas y las diez últimas filas del dataset original)

Muestre el resultado y las características del arreglo.

In [ ]:
# Seleccionar las columnas del dataset original
columnas = np.hstack((peliculas_disney[:, :3], peliculas_disney[:, -3:]))

# Crear el nuevo arreglo 'arreglo_00' combinando las columnas\
# seleccionadas y las filas deseadas
arreglo_00 = np.vstack((columnas[:10], columnas[-10:]))

# Muestra el resultado y las características del arreglo_00
print(f"arreglo_00: \n {arreglo_00}")
print("\nCaracterísticas del arreglo_00:")
print(f"La forma del arreglo_00 es: {arreglo_00.shape}")
print(f"La dimensión del arreglo_00 es: {arreglo_00.ndim}")
print(f"Número de filas: {arreglo_00.shape[0]}")
print(f"Número de columnas: {arreglo_00.shape[1]}")
pep8(_ih)

arreglo_00: 
 [['Índice' 'title' 'Production company' 'Adaptation by' 'Traditional'
  'Simplified']
 ['0' 'Academy Award Review of' 'Walt Disney Productions' '0' '0' '0']
 ['1' 'Snow White and the Seven Dwarfs' 'Walt Disney Productions' '0' '0'
  '0']
 ['2' 'Pinocchio' 'Walt Disney Productions' '0' '0' '0']
 ['3' 'Fantasia' 'Walt Disney Productions' '0' '0' '0']
 ['4' 'The Reluctant Dragon' 'Walt Disney Productions' '0' '0' '0']
 ['5' 'Dumbo' 'Walt Disney Productions' '0' '0' '0']
 ['7' 'Saludos Amigos' 'Walt Disney Productions' '0' '0' '0']
 ['8' 'Victory Through Air Power' 'Walt Disney Productions' '0' '0' '0']
 ['9' 'The Three Caballeros' 'Walt Disney Productions' '0' '0' '0']
 ['422' 'Black Is King'
  "('Parkwood Entertainment'; 'Walt Disney Pictures')" '0' '0' '0']
 ['423' 'Magic Camp' "('Walt Disney Pictures'; 'Team Todd')" '0' '0' '0']
 ['424' 'The One and Only Ivan'
  "('Walt Disney Pictures'; 'Jolie Pas Productions')" '0' '0' '0']
 ['425' 'Mulan'
  "('Walt Disney Pictures'; 'J

## arreglo_01

Cree el arreglo_01 (diez columnas y doce filas) a partir del arreglo_00.

Muestre el resultado y las características del arreglo.


In [ ]:
# Obtiene las 12 filas y 10 columnas del 'arreglo_00'
arreglo_01 = arreglo_00.reshape(12, 10)

# Muestra el resultado y las características del arreglo_01
print(f"arreglo_01: \n {arreglo_01}")
print("\nCaracterísticas del arreglo arreglo_01:")
print(f"La forma del arreglo arreglo_01 es: {arreglo_01.shape}")
print(f"La dimensión del arreglo arreglo_01 es: {arreglo_01.ndim}")
print(f"Número de filas: {arreglo_01.shape[0]}")
print(f"Número de columnas: {arreglo_01.shape[1]}")
pep8(_ih)

arreglo_01: 
 [['Índice' 'title' 'Production company' 'Adaptation by' 'Traditional'
  'Simplified' '0' 'Academy Award Review of' 'Walt Disney Productions'
  '0']
 ['0' '0' '1' 'Snow White and the Seven Dwarfs' 'Walt Disney Productions'
  '0' '0' '0' '2' 'Pinocchio']
 ['Walt Disney Productions' '0' '0' '0' '3' 'Fantasia'
  'Walt Disney Productions' '0' '0' '0']
 ['4' 'The Reluctant Dragon' 'Walt Disney Productions' '0' '0' '0' '5'
  'Dumbo' 'Walt Disney Productions' '0']
 ['0' '0' '7' 'Saludos Amigos' 'Walt Disney Productions' '0' '0' '0' '8'
  'Victory Through Air Power']
 ['Walt Disney Productions' '0' '0' '0' '9' 'The Three Caballeros'
  'Walt Disney Productions' '0' '0' '0']
 ['422' 'Black Is King'
  "('Parkwood Entertainment'; 'Walt Disney Pictures')" '0' '0' '0' '423'
  'Magic Camp' "('Walt Disney Pictures'; 'Team Todd')" '0']
 ['0' '0' '424' 'The One and Only Ivan'
  "('Walt Disney Pictures'; 'Jolie Pas Productions')" '0' '0' '0' '425'
  'Mulan']
 ["('Walt Disney Pictures'; 'Jaso

## arreglo_02

Cree el arreglo_02 (cinco columnas y diez filas) a partir del dataset original. Todos los datos deben ser números.

Agregue al arreglo_02 lo siguiente:

* una columna con todos los valores iguales a cinco
* una columna con todos los valores iguales a uno
* una columna con números aleatorios provenientes de una distribución normal de media 0 y desviación típica 1
* una columna con números aleatorios enteros en el intervalo 200 a 300
* una columna con números aleatorios binarios (0,1)

Muestre el resultado y las características del arreglo.

In [ ]:
# Importar la librería random
import random

# Seleccionar columnas numéricas del dataset
id = peliculas_disney[1:11, :1]
running_time = peliculas_disney[1:11, 7:8]
budget = peliculas_disney[1:11, 8:9]
box_office = peliculas_disney[1:11, 9:10]
imdb = peliculas_disney[1:11, 11:12]

# Crear una columna con todos los valores iguales a cinco
columna_cinco = np.full((10, 1), 5)

# Crear una columna con todos los valores iguales a uno
columna_uno = np.full((10, 1), 1)

# Crear una columna con números aleatorios de una distribución\
# normal (media 0, desviación estándar 1)
columna_normal = np.random.normal(0, 1, size=(10, 1))

# Crear una columna con números aleatorios enteros en el intervalo\
# [200, 300]
columna_enteros = np.random.randint(200, 301, size=(10, 1))

# Crear una columna con números aleatorios binarios (0 o 1)
columna_binarios = np.random.randint(0, 2, size=(10, 1))

# Concatenar todas las columnas horizontalmente para formar el arreglo_02
arreglo_02 = np.hstack((id, running_time, budget, box_office, imdb,
                        columna_cinco, columna_uno, columna_normal,
                        columna_enteros, columna_binarios))

# Muestra el resultado y las características del arreglo_02
print(f"arreglo_02: \n {arreglo_02}")
print("\nCaracterísticas del arreglo arreglo_02:")
print(f"La forma del arreglo arreglo_02 es: {arreglo_02.shape}")
print(f"La dimensión del arreglo arreglo_02 es: {arreglo_02.ndim}")
print(f"Número de filas: {arreglo_02.shape[0]}")
print(f"Número de columnas: {arreglo_02.shape[1]}")
pep8(_ih)

arreglo_02: 
 [['0' '41.0' '0' '0' '7.2' '5' '1' '0.259164540442896' '258' '0']
 ['1' '83.0' '1490000.0' '418000000.0' '7.6' '5' '1' '0.6890416313024238'
  '270' '1']
 ['2' '88.0' '2600000.0' '164000000.0' '7.4' '5' '1'
  '-1.0523270136540646' '202' '1']
 ['3' '126.0' '2280000.0' '83300000.0' '7.8' '5' '1'
  '-0.26535160222294485' '274' '0']
 ['4' '74.0' '600000.0' '960000.0' '6.9' '5' '1' '0.4139447614188138'
  '246' '0']
 ['5' '64.0' '950000.0' '1300000.0' '7.2' '5' '1' '0.4160221621804262'
  '217' '0']
 ['7' '42.0' '0' '1135000.0' '6.1' '5' '1' '-1.2014866457362228' '300'
  '1']
 ['8' '65.0' '788000.0' '799000.0' '6.5' '5' '1' '-0.2893226625066224'
  '226' '1']
 ['9' '71.0' '0' '3355000.0' '6.4' '5' '1' '0.6228941056870442' '296' '0']
 ['10' '75.0' '1350000.0' '3275000.0' '6.3' '5' '1'
  '-0.20234096587048275' '248' '0']]

Características del arreglo arreglo_02:
La forma del arreglo arreglo_02 es: (10, 10)
La dimensión del arreglo arreglo_02 es: 2
Número de filas: 10
Número de colum

# Operaciones con dataset

## arreglo_03

Cree el arreglo_03 como la matriz transpuesta del arreglo_02 obtenido en el ejercicio anterior.

Encuentre la inversa del arreglo_03 y multiplíquela por el arreglo_03.

Muestre los arreglos obtenidos y las características de cada uno de ellos.

In [ ]:
# Calcula la matriz transpuesta (arreglo_03)
arreglo_03 = arreglo_02.T

# Convierte todos los elementos del arreglo a tipo 'float64'
arreglo_03 = arreglo_03.astype(np.float64)

# Encuentra la inversa de arreglo_03
inversa_arreglo_03 = np.linalg.inv(arreglo_03)

# Multiplica la inversa por arreglo_03
resultado_multiplicacion = np.dot(inversa_arreglo_03, arreglo_03)

# Muestra el arreglo 3 y sus características
print(f"arreglo_03 (Transpuesta de arreglo_02): \n {arreglo_03}")
print("\nCaracterísticas de arreglo_03:")
print(f"La forma del arreglo_03 es: {arreglo_03.shape}")
print(f"La dimensión del arreglo_03 es: {arreglo_03.ndim}")
print(f"Número de filas: {arreglo_03.shape[0]}")
print(f"Número de columnas: {arreglo_03.shape[1]} \n")

# Muestra la inversa del arreglo 3 y sus características
print(f"Inversa del arreglo_03: \n {inversa_arreglo_03}")
print("\nCaracterísticas de inversa_arreglo_03:")
print(f"La forma del arreglo inversa_arreglo_03 es: \
{inversa_arreglo_03.shape}")
print(f"La dimensión del arreglo inversa_arreglo_03 es: \
{inversa_arreglo_03.ndim}")
print(f"Número de filas: {inversa_arreglo_03.shape[0]}")
print(f"Número de columnas: {inversa_arreglo_03.shape[1]} \n")

# Muestra la multiplicación inversa_arreglo_03 x arreglo_03 del arreglo 3\
# y sus características
print(f"Resultado de la multiplicación inversa_arreglo_03 x arreglo_03:\
\n {resultado_multiplicacion}")
print("\nCaracterísticas del resultado de la multiplicación:")
print(f"La forma del arreglo resultado_multiplicacion es: \
{resultado_multiplicacion.shape}")
print(f"La dimensión del arreglo resultado_multiplicacion es: \
{resultado_multiplicacion.ndim}")
print(f"Número de filas: {resultado_multiplicacion.shape[0]}")
print(f"Número de columnas: {resultado_multiplicacion.shape[1]}")
pep8(_ih)

arreglo_03 (Transpuesta de arreglo_02): 
 [[ 0.00000000e+00  1.00000000e+00  2.00000000e+00  3.00000000e+00
   4.00000000e+00  5.00000000e+00  7.00000000e+00  8.00000000e+00
   9.00000000e+00  1.00000000e+01]
 [ 4.10000000e+01  8.30000000e+01  8.80000000e+01  1.26000000e+02
   7.40000000e+01  6.40000000e+01  4.20000000e+01  6.50000000e+01
   7.10000000e+01  7.50000000e+01]
 [ 0.00000000e+00  1.49000000e+06  2.60000000e+06  2.28000000e+06
   6.00000000e+05  9.50000000e+05  0.00000000e+00  7.88000000e+05
   0.00000000e+00  1.35000000e+06]
 [ 0.00000000e+00  4.18000000e+08  1.64000000e+08  8.33000000e+07
   9.60000000e+05  1.30000000e+06  1.13500000e+06  7.99000000e+05
   3.35500000e+06  3.27500000e+06]
 [ 7.20000000e+00  7.60000000e+00  7.40000000e+00  7.80000000e+00
   6.90000000e+00  7.20000000e+00  6.10000000e+00  6.50000000e+00
   6.40000000e+00  6.30000000e+00]
 [ 5.00000000e+00  5.00000000e+00  5.00000000e+00  5.00000000e+00
   5.00000000e+00  5.00000000e+00  5.00000000e+00  5.0000

## arreglo_04

Cree el arreglo_04 como la suma del arreglo_03 con su transpuesta.

Muestre el resultado y las características del arreglo.

In [ ]:
# Calcula la suma del arreglo_03 con su transpuesta
arreglo_04 = arreglo_03 + arreglo_03.T

# Muestra el resultado y las características del arreglo_04
print(f"arreglo_04: \n {arreglo_04}")
print("\nCaracterísticas del arreglo arreglo_04:")
print(f"La forma del arreglo arreglo_04 es: {arreglo_04.shape}")
print(f"La dimensión del arreglo arreglo_04 es: {arreglo_04.ndim}")
print(f"Número de filas: {arreglo_04.shape[0]}")
print(f"Número de columnas: {arreglo_04.shape[1]}")
pep8(_ih)

arreglo_04: 
 [[ 0.00000000e+00  4.20000000e+01  2.00000000e+00  3.00000000e+00
   1.12000000e+01  1.00000000e+01  8.00000000e+00  8.25916454e+00
   2.67000000e+02  1.00000000e+01]
 [ 4.20000000e+01  1.66000000e+02  1.49008800e+06  4.18000126e+08
   8.16000000e+01  6.90000000e+01  4.30000000e+01  6.56890416e+01
   3.41000000e+02  7.60000000e+01]
 [ 2.00000000e+00  1.49008800e+06  5.20000000e+06  1.66280000e+08
   6.00007400e+05  9.50005000e+05  1.00000000e+00  7.87998948e+05
   2.02000000e+02  1.35000100e+06]
 [ 3.00000000e+00  4.18000126e+08  1.66280000e+08  1.66600000e+08
   9.60007800e+05  1.30000500e+06  1.13500100e+06  7.98999735e+05
   3.35527400e+06  3.27500000e+06]
 [ 1.12000000e+01  8.16000000e+01  6.00007400e+05  9.60007800e+05
   1.38000000e+01  1.22000000e+01  7.10000000e+00  6.91394476e+00
   2.52400000e+02  6.30000000e+00]
 [ 1.00000000e+01  6.90000000e+01  9.50005000e+05  1.30000500e+06
   1.22000000e+01  1.00000000e+01  6.00000000e+00  5.41602216e+00
   2.22000000e+02  

## arreglo_05

Cree el arreglo_05 a partir del arreglo_04 reemplazando los valores inferiores o iguales a la media por cero, y los valores superiores a la media por cinco.

Muestre el resultado y las características del arreglo.

In [ ]:
# Calcula la media de todos los valores en el arreglo_04
media_arreglo_04 = np.mean(arreglo_04)

# Reemplaza los valores inferiores o iguales a la media por cero y los \
# valores superiores a la media por cinco
arreglo_05 = np.where(arreglo_04 <= media_arreglo_04, 0, 5)

# Muestra el resultado y las características del arreglo_05
print(f"arreglo_05: \n {arreglo_05}")
print("\nCaracterísticas del arreglo arreglo_05:")
print(f"La forma del arreglo arreglo_05 es: {arreglo_05.shape}")
print(f"La dimensión del arreglo arreglo_05 es: {arreglo_05.ndim}")
print(f"Número de filas: {arreglo_05.shape[0]}")
print(f"Número de columnas: {arreglo_05.shape[1]}")
pep8(_ih)

arreglo_05: 
 [[0 0 0 0 0 0 0 0 0 0]
 [0 0 0 5 0 0 0 0 0 0]
 [0 0 0 5 0 0 0 0 0 0]
 [0 5 5 5 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]]

Características del arreglo arreglo_05:
La forma del arreglo arreglo_05 es: (10, 10)
La dimensión del arreglo arreglo_05 es: 2
Número de filas: 10
Número de columnas: 10



## arreglo_06

Cree el arreglo_06 **juntando de forma horizontal** el arreglo_03 y el arreglo_04.

Muestre el resultado y las características del arreglo.



In [ ]:
# Concatena los arreglos horizontalmente para formar arreglo_06
arreglo_06 = np.hstack((arreglo_03, arreglo_04))

# Muestra el resultado y las características del arreglo_06
print(f"arreglo_06: \n {arreglo_06}")
print("\nCaracterísticas del arreglo arreglo_06:")
print(f"La forma del arreglo arreglo_06 es: {arreglo_06.shape}")
print(f"La dimensión del arreglo arreglo_06 es: {arreglo_06.ndim}")
print(f"Número de filas: {arreglo_06.shape[0]}")
print(f"Número de columnas: {arreglo_06.shape[1]}")
pep8(_ih)

arreglo_06: 
 [[ 0.00000000e+00  1.00000000e+00  2.00000000e+00  3.00000000e+00
   4.00000000e+00  5.00000000e+00  7.00000000e+00  8.00000000e+00
   9.00000000e+00  1.00000000e+01  0.00000000e+00  4.20000000e+01
   2.00000000e+00  3.00000000e+00  1.12000000e+01  1.00000000e+01
   8.00000000e+00  8.25916454e+00  2.67000000e+02  1.00000000e+01]
 [ 4.10000000e+01  8.30000000e+01  8.80000000e+01  1.26000000e+02
   7.40000000e+01  6.40000000e+01  4.20000000e+01  6.50000000e+01
   7.10000000e+01  7.50000000e+01  4.20000000e+01  1.66000000e+02
   1.49008800e+06  4.18000126e+08  8.16000000e+01  6.90000000e+01
   4.30000000e+01  6.56890416e+01  3.41000000e+02  7.60000000e+01]
 [ 0.00000000e+00  1.49000000e+06  2.60000000e+06  2.28000000e+06
   6.00000000e+05  9.50000000e+05  0.00000000e+00  7.88000000e+05
   0.00000000e+00  1.35000000e+06  2.00000000e+00  1.49008800e+06
   5.20000000e+06  1.66280000e+08  6.00007400e+05  9.50005000e+05
   1.00000000e+00  7.87998948e+05  2.02000000e+02  1.3500010

## arreglo_07

Cree el arreglo_07 **juntando de forma vertical** el arreglo_03 y el arreglo_04

In [ ]:
# Concatena los arreglos verticalmente para formar arreglo_07
arreglo_07 = np.vstack((arreglo_03, arreglo_04))

# Muestra el resultado y las características del arreglo_07
print(f"arreglo_07: \n {arreglo_07}")
print("\nCaracterísticas del arreglo arreglo_07:")
print(f"La forma del arreglo arreglo_07 es: {arreglo_07.shape}")
print(f"La dimensión del arreglo arreglo_07 es: {arreglo_07.ndim}")
print(f"Número de filas: {arreglo_07.shape[0]}")
print(f"Número de columnas: {arreglo_07.shape[1]}")
pep8(_ih)

arreglo_07: 
 [[ 0.00000000e+00  1.00000000e+00  2.00000000e+00  3.00000000e+00
   4.00000000e+00  5.00000000e+00  7.00000000e+00  8.00000000e+00
   9.00000000e+00  1.00000000e+01]
 [ 4.10000000e+01  8.30000000e+01  8.80000000e+01  1.26000000e+02
   7.40000000e+01  6.40000000e+01  4.20000000e+01  6.50000000e+01
   7.10000000e+01  7.50000000e+01]
 [ 0.00000000e+00  1.49000000e+06  2.60000000e+06  2.28000000e+06
   6.00000000e+05  9.50000000e+05  0.00000000e+00  7.88000000e+05
   0.00000000e+00  1.35000000e+06]
 [ 0.00000000e+00  4.18000000e+08  1.64000000e+08  8.33000000e+07
   9.60000000e+05  1.30000000e+06  1.13500000e+06  7.99000000e+05
   3.35500000e+06  3.27500000e+06]
 [ 7.20000000e+00  7.60000000e+00  7.40000000e+00  7.80000000e+00
   6.90000000e+00  7.20000000e+00  6.10000000e+00  6.50000000e+00
   6.40000000e+00  6.30000000e+00]
 [ 5.00000000e+00  5.00000000e+00  5.00000000e+00  5.00000000e+00
   5.00000000e+00  5.00000000e+00  5.00000000e+00  5.00000000e+00
   5.00000000e+00  